export const RoundStats = [
    {
        'Round Tier': 1,
        'Last Round': 4,
        'Min Enemies per Wave': 6,
        'Max Enemies per Wave': 9,
        'Tier 1 Enemies Proportion': 1,
        'Tier 2 Enemies Proportion': 0,
        'Tier 3 Enemies Proportion': 0,
    },
    {
        'Round Tier': 2,
        'Last Round': 8,
        'Min Enemies per Wave': 7,
        'Max Enemies per Wave': 11,
        'Tier 1 Enemies Proportion': 0.96,
        'Tier 2 Enemies Proportion': 0.03,
        'Tier 3 Enemies Proportion': 0.01,
    },
    {
        'Round Tier': 3,
        'Last Round': 12,
        'Min Enemies per Wave': 8,
        'Max Enemies per Wave': 13,
        'Tier 1 Enemies Proportion': 0.92,
        'Tier 2 Enemies Proportion': 0.06,
        'Tier 3 Enemies Proportion': 0.02,
    },
    {
        'Round Tier': 4,
        'Last Round': 16,
        'Min Enemies per Wave': 9,
        'Max Enemies per Wave': 15,
        'Tier 1 Enemies Proportion': 0.88,
        'Tier 2 Enemies Proportion': 0.09,
        'Tier 3 Enemies Proportion': 0.03,
    },
    {
        'Round Tier': 5,
        'Last Round': 20,
        'Min Enemies per Wave': 10,
        'Max Enemies per Wave': 17,
        'Tier 1 Enemies Proportion': 0.84,
        'Tier 2 Enemies Proportion': 0.12,
        'Tier 3 Enemies Proportion': 0.04,
    },
    {
        'Round Tier': 6,
        'Last Round': 24,
        'Min Enemies per Wave': 11,
        'Max Enemies per Wave': 19,
        'Tier 1 Enemies Proportion': 0.8,
        'Tier 2 Enemies Proportion': 0.15,
        'Tier 3 Enemies Proportion': 0.05,
    },
    {
        'Round Tier': 7,
        'Last Round': 28,
        'Min Enemies per Wave': 12,
        'Max Enemies per Wave': 21,
        'Tier 1 Enemies Proportion': 0.76,
        'Tier 2 Enemies Proportion': 0.18,
        'Tier 3 Enemies Proportion': 0.06,
    },
    {
        'Round Tier': 8,
        'Last Round': 32,
        'Min Enemies per Wave': 13,
        'Max Enemies per Wave': 23,
        'Tier 1 Enemies Proportion': 0.72,
        'Tier 2 Enemies Proportion': 0.21,
        'Tier 3 Enemies Proportion': 0.07,
    },
    {
        'Round Tier': 9,
        'Last Round': 36,
        'Min Enemies per Wave': 14,
        'Max Enemies per Wave': 25,
        'Tier 1 Enemies Proportion': 0.68,
        'Tier 2 Enemies Proportion': 0.24,
        'Tier 3 Enemies Proportion': 0.08,
    },
    {
        'Round Tier': 10,
        'Last Round': 40,
        'Min Enemies per Wave': 15,
        'Max Enemies per Wave': 27,
        'Tier 1 Enemies Proportion': 0.64,
        'Tier 2 Enemies Proportion': 0.27,
        'Tier 3 Enemies Proportion': 0.09,
    },
    {
        'Round Tier': 11,
        'Last Round': 44,
        'Min Enemies per Wave': 16,
        'Max Enemies per Wave': 29,
        'Tier 1 Enemies Proportion': 0.6,
        'Tier 2 Enemies Proportion': 0.3,
        'Tier 3 Enemies Proportion': 0.1,
    },
    {
        'Round Tier': 12,
        'Last Round': 48,
        'Min Enemies per Wave': 17,
        'Max Enemies per Wave': 31,
        'Tier 1 Enemies Proportion': 0.56,
        'Tier 2 Enemies Proportion': 0.33,
        'Tier 3 Enemies Proportion': 0.11,
    },
    {
        'Round Tier': 13,
        'Last Round': 52,
        'Min Enemies per Wave': 18,
        'Max Enemies per Wave': 33,
        'Tier 1 Enemies Proportion': 0.52,
        'Tier 2 Enemies Proportion': 0.36,
        'Tier 3 Enemies Proportion': 0.12,
    },
    {
        'Round Tier': 14,
        'Last Round': 56,
        'Min Enemies per Wave': 19,
        'Max Enemies per Wave': 35,
        'Tier 1 Enemies Proportion': 0.48,
        'Tier 2 Enemies Proportion': 0.39,
        'Tier 3 Enemies Proportion': 0.13,
    },
    {
        'Round Tier': 15,
        'Last Round': 60,
        'Min Enemies per Wave': 20,
        'Max Enemies per Wave': 37,
        'Tier 1 Enemies Proportion': 0.44,
        'Tier 2 Enemies Proportion': 0.42,
        'Tier 3 Enemies Proportion': 0.14,
    },
    {
        'Round Tier': 16,
        'Last Round': 64,
        'Min Enemies per Wave': 21,
        'Max Enemies per Wave': 39,
        'Tier 1 Enemies Proportion': 0.4,
        'Tier 2 Enemies Proportion': 0.45,
        'Tier 3 Enemies Proportion': 0.15,
    },
    {
        'Round Tier': 17,
        'Last Round': 68,
        'Min Enemies per Wave': 22,
        'Max Enemies per Wave': 41,
        'Tier 1 Enemies Proportion': 0.36,
        'Tier 2 Enemies Proportion': 0.48,
        'Tier 3 Enemies Proportion': 0.16,
    },
    {
        'Round Tier': 18,
        'Last Round': 72,
        'Min Enemies per Wave': 23,
        'Max Enemies per Wave': 43,
        'Tier 1 Enemies Proportion': 0.32,
        'Tier 2 Enemies Proportion': 0.51,
        'Tier 3 Enemies Proportion': 0.17,
    },
    {
        'Round Tier': 19,
        'Last Round': 76,
        'Min Enemies per Wave': 24,
        'Max Enemies per Wave': 45,
        'Tier 1 Enemies Proportion': 0.28,
        'Tier 2 Enemies Proportion': 0.54,
        'Tier 3 Enemies Proportion': 0.18,
    },
    {
        'Round Tier': 20,
        'Last Round': 80,
        'Min Enemies per Wave': 25,
        'Max Enemies per Wave': 47,
        'Tier 1 Enemies Proportion': 0.24,
        'Tier 2 Enemies Proportion': 0.57,
        'Tier 3 Enemies Proportion': 0.19,
    },
    {
        'Round Tier': 21,
        'Last Round': 84,
        'Min Enemies per Wave': 26,
        'Max Enemies per Wave': 49,
        'Tier 1 Enemies Proportion': 0.2,
        'Tier 2 Enemies Proportion': 0.6,
        'Tier 3 Enemies Proportion': 0.2,
    },
    {
        'Round Tier': 22,
        'Last Round': 88,
        'Min Enemies per Wave': 27,
        'Max Enemies per Wave': 51,
        'Tier 1 Enemies Proportion': 0.16,
        'Tier 2 Enemies Proportion': 0.63,
        'Tier 3 Enemies Proportion': 0.21,
    },
    {
        'Round Tier': 23,
        'Last Round': 92,
        'Min Enemies per Wave': 28,
        'Max Enemies per Wave': 53,
        'Tier 1 Enemies Proportion': 0.12,
        'Tier 2 Enemies Proportion': 0.66,
        'Tier 3 Enemies Proportion': 0.22,
    },
    {
        'Round Tier': 24,
        'Last Round': 96,
        'Min Enemies per Wave': 29,
        'Max Enemies per Wave': 55,
        'Tier 1 Enemies Proportion': 0.08,
        'Tier 2 Enemies Proportion': 0.69,
        'Tier 3 Enemies Proportion': 0.23,
    },
    {
        'Round Tier': 25,
        'Last Round': 100,
        'Min Enemies per Wave': 30,
        'Max Enemies per Wave': 57,
        'Tier 1 Enemies Proportion': 0.04,
        'Tier 2 Enemies Proportion': 0.72,
        'Tier 3 Enemies Proportion': 0.24,
    },
] as const;

export default RoundStats;
