export const SmallDiamondEnemyStats = [
    {
        'Round Tier': 1,
        'Number of Shots Needed To Destroy Player': 10,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 220,
        'Attack Speed': 0.5,
        'Enemies Lifepoints': 24,
        'Tier 1 Frame Speed (Number Frames to HalfScreen Distance)': 110,
    },
    {
        'Round Tier': 2,
        'Number of Shots Needed To Destroy Player': 10,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 220,
        'Attack Speed': 0.5,
        'Enemies Lifepoints': 63,
        'Tier 1 Frame Speed (Number Frames to HalfScreen Distance)': 107.6,
    },
    {
        'Round Tier': 3,
        'Number of Shots Needed To Destroy Player': 10,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 220,
        'Attack Speed': 0.5,
        'Enemies Lifepoints': 116,
        'Tier 1 Frame Speed (Number Frames to HalfScreen Distance)': 106.4,
    },
    {
        'Round Tier': 4,
        'Number of Shots Needed To Destroy Player': 10,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 220,
        'Attack Speed': 0.5,
        'Enemies Lifepoints': 183,
        'Tier 1 Frame Speed (Number Frames to HalfScreen Distance)': 105.2,
    },
    {
        'Round Tier': 5,
        'Number of Shots Needed To Destroy Player': 9,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 220,
        'Attack Speed': 0.5,
        'Enemies Lifepoints': 265,
        'Tier 1 Frame Speed (Number Frames to HalfScreen Distance)': 104,
    },
    {
        'Round Tier': 6,
        'Number of Shots Needed To Destroy Player': 9,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 220,
        'Attack Speed': 0.5,
        'Enemies Lifepoints': 361,
        'Tier 1 Frame Speed (Number Frames to HalfScreen Distance)': 102.8,
    },
    {
        'Round Tier': 7,
        'Number of Shots Needed To Destroy Player': 9,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 220,
        'Attack Speed': 0.5,
        'Enemies Lifepoints': 472,
        'Tier 1 Frame Speed (Number Frames to HalfScreen Distance)': 101.6,
    },
    {
        'Round Tier': 8,
        'Number of Shots Needed To Destroy Player': 9,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 220,
        'Attack Speed': 0.5,
        'Enemies Lifepoints': 597,
        'Tier 1 Frame Speed (Number Frames to HalfScreen Distance)': 100.4,
    },
    {
        'Round Tier': 9,
        'Number of Shots Needed To Destroy Player': 9,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 220,
        'Attack Speed': 0.5,
        'Enemies Lifepoints': 737,
        'Tier 1 Frame Speed (Number Frames to HalfScreen Distance)': 99.2,
    },
    {
        'Round Tier': 10,
        'Number of Shots Needed To Destroy Player': 9,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 220,
        'Attack Speed': 0.5,
        'Enemies Lifepoints': 891,
        'Tier 1 Frame Speed (Number Frames to HalfScreen Distance)': 98,
    },
    {
        'Round Tier': 11,
        'Number of Shots Needed To Destroy Player': 9,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 220,
        'Attack Speed': 0.5,
        'Enemies Lifepoints': 1060,
        'Tier 1 Frame Speed (Number Frames to HalfScreen Distance)': 96.8,
    },
    {
        'Round Tier': 12,
        'Number of Shots Needed To Destroy Player': 9,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 220,
        'Attack Speed': 0.5,
        'Enemies Lifepoints': 1243,
        'Tier 1 Frame Speed (Number Frames to HalfScreen Distance)': 95.6,
    },
    {
        'Round Tier': 13,
        'Number of Shots Needed To Destroy Player': 8,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 220,
        'Attack Speed': 0.5,
        'Enemies Lifepoints': 1440,
        'Tier 1 Frame Speed (Number Frames to HalfScreen Distance)': 94.4,
    },
    {
        'Round Tier': 14,
        'Number of Shots Needed To Destroy Player': 8,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 220,
        'Attack Speed': 0.5,
        'Enemies Lifepoints': 1652,
        'Tier 1 Frame Speed (Number Frames to HalfScreen Distance)': 93.2,
    },
    {
        'Round Tier': 15,
        'Number of Shots Needed To Destroy Player': 8,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 220,
        'Attack Speed': 0.5,
        'Enemies Lifepoints': 1879,
        'Tier 1 Frame Speed (Number Frames to HalfScreen Distance)': 92,
    },
    {
        'Round Tier': 16,
        'Number of Shots Needed To Destroy Player': 8,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 220,
        'Attack Speed': 0.5,
        'Enemies Lifepoints': 2120,
        'Tier 1 Frame Speed (Number Frames to HalfScreen Distance)': 90.8,
    },
    {
        'Round Tier': 17,
        'Number of Shots Needed To Destroy Player': 8,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 220,
        'Attack Speed': 0.5,
        'Enemies Lifepoints': 2375,
        'Tier 1 Frame Speed (Number Frames to HalfScreen Distance)': 89.6,
    },
    {
        'Round Tier': 18,
        'Number of Shots Needed To Destroy Player': 8,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 220,
        'Attack Speed': 0.5,
        'Enemies Lifepoints': 2645,
        'Tier 1 Frame Speed (Number Frames to HalfScreen Distance)': 88.4,
    },
    {
        'Round Tier': 19,
        'Number of Shots Needed To Destroy Player': 8,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 220,
        'Attack Speed': 0.5,
        'Enemies Lifepoints': 2929,
        'Tier 1 Frame Speed (Number Frames to HalfScreen Distance)': 87.2,
    },
    {
        'Round Tier': 20,
        'Number of Shots Needed To Destroy Player': 8,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 220,
        'Attack Speed': 0.5,
        'Enemies Lifepoints': 3228,
        'Tier 1 Frame Speed (Number Frames to HalfScreen Distance)': 86,
    },
    {
        'Round Tier': 21,
        'Number of Shots Needed To Destroy Player': 7,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 220,
        'Attack Speed': 0.5,
        'Enemies Lifepoints': 3541,
        'Tier 1 Frame Speed (Number Frames to HalfScreen Distance)': 84.8,
    },
    {
        'Round Tier': 22,
        'Number of Shots Needed To Destroy Player': 7,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 220,
        'Attack Speed': 0.5,
        'Enemies Lifepoints': 3869,
        'Tier 1 Frame Speed (Number Frames to HalfScreen Distance)': 83.6,
    },
    {
        'Round Tier': 23,
        'Number of Shots Needed To Destroy Player': 7,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 220,
        'Attack Speed': 0.5,
        'Enemies Lifepoints': 4211,
        'Tier 1 Frame Speed (Number Frames to HalfScreen Distance)': 82.4,
    },
    {
        'Round Tier': 24,
        'Number of Shots Needed To Destroy Player': 7,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 220,
        'Attack Speed': 0.5,
        'Enemies Lifepoints': 4567,
        'Tier 1 Frame Speed (Number Frames to HalfScreen Distance)': 81.2,
    },
    {
        'Round Tier': 25,
        'Number of Shots Needed To Destroy Player': 7,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 220,
        'Attack Speed': 0.5,
        'Enemies Lifepoints': 4938,
        'Tier 1 Frame Speed (Number Frames to HalfScreen Distance)': 80,
    },
] as const;

export default SmallDiamondEnemyStats;
