export const FuelChargeShotDamage = [
    {
        'Number Of Boost': 0,
        'Laser Level 1 Damage': 0,
        'Laser Level 1 Base Damage Debuf (%)': 3.34,
        'Laser Level 1 Money Boost (%)': 11,
        'Laser Level 2 Damage': 0,
        'Laser Level 2 Base Damage Debuf (%)': 3.34,
        'Laser Level 2 Money Boost (%)': 11,
        'Laser Level 2 Paralyze Probability (%)': 30,
        'Laser Level 3 Damage': 0,
        'Laser Level 3 Base Damage Debuf (%)': 3.34,
        'Laser Level 3 Money Boost (%)': 16.67,
        'Laser Level 3 Explosive Resistance Debuf (%)': 6.67,
        'Laser Level 3 Energy Resistance Debuf (%)': 5,
        'Laser Level 3 Corrosive Damage': 3,
    },
    {
        'Number Of Boost': 1,
        'Laser Level 1 Damage': 0,
        'Laser Level 1 Base Damage Debuf (%)': 3.61,
        'Laser Level 1 Money Boost (%)': 11.9,
        'Laser Level 2 Damage': 0,
        'Laser Level 2 Base Damage Debuf (%)': 6.52,
        'Laser Level 2 Money Boost (%)': 11.9,
        'Laser Level 2 Paralyze Probability (%)': 30.8,
        'Laser Level 3 Damage': 0,
        'Laser Level 3 Base Damage Debuf (%)': 11.55,
        'Laser Level 3 Money Boost (%)': 18.01,
        'Laser Level 3 Explosive Resistance Debuf (%)': 6.94,
        'Laser Level 3 Energy Resistance Debuf (%)': 5.2,
        'Laser Level 3 Corrosive Damage': 3,
    },
    {
        'Number Of Boost': 2,
        'Laser Level 1 Damage': 0,
        'Laser Level 1 Base Damage Debuf (%)': 3.88,
        'Laser Level 1 Money Boost (%)': 12.79,
        'Laser Level 2 Damage': 0,
        'Laser Level 2 Base Damage Debuf (%)': 6.75,
        'Laser Level 2 Money Boost (%)': 12.79,
        'Laser Level 2 Paralyze Probability (%)': 31.6,
        'Laser Level 3 Damage': 0,
        'Laser Level 3 Base Damage Debuf (%)': 11.76,
        'Laser Level 3 Money Boost (%)': 19.34,
        'Laser Level 3 Explosive Resistance Debuf (%)': 7.21,
        'Laser Level 3 Energy Resistance Debuf (%)': 5.4,
        'Laser Level 3 Corrosive Damage': 6,
    },
    {
        'Number Of Boost': 3,
        'Laser Level 1 Damage': 0,
        'Laser Level 1 Base Damage Debuf (%)': 4.14,
        'Laser Level 1 Money Boost (%)': 13.69,
        'Laser Level 2 Damage': 0,
        'Laser Level 2 Base Damage Debuf (%)': 6.99,
        'Laser Level 2 Money Boost (%)': 13.69,
        'Laser Level 2 Paralyze Probability (%)': 32.4,
        'Laser Level 3 Damage': 0,
        'Laser Level 3 Base Damage Debuf (%)': 11.98,
        'Laser Level 3 Money Boost (%)': 20.67,
        'Laser Level 3 Explosive Resistance Debuf (%)': 7.48,
        'Laser Level 3 Energy Resistance Debuf (%)': 5.6,
        'Laser Level 3 Corrosive Damage': 9,
    },
    {
        'Number Of Boost': 4,
        'Laser Level 1 Damage': 0,
        'Laser Level 1 Base Damage Debuf (%)': 4.41,
        'Laser Level 1 Money Boost (%)': 14.58,
        'Laser Level 2 Damage': 0,
        'Laser Level 2 Base Damage Debuf (%)': 7.23,
        'Laser Level 2 Money Boost (%)': 14.58,
        'Laser Level 2 Paralyze Probability (%)': 33.2,
        'Laser Level 3 Damage': 0,
        'Laser Level 3 Base Damage Debuf (%)': 12.19,
        'Laser Level 3 Money Boost (%)': 22.01,
        'Laser Level 3 Explosive Resistance Debuf (%)': 7.74,
        'Laser Level 3 Energy Resistance Debuf (%)': 5.8,
        'Laser Level 3 Corrosive Damage': 12,
    },
    {
        'Number Of Boost': 5,
        'Laser Level 1 Damage': 0,
        'Laser Level 1 Base Damage Debuf (%)': 4.68,
        'Laser Level 1 Money Boost (%)': 15.47,
        'Laser Level 2 Damage': 0,
        'Laser Level 2 Base Damage Debuf (%)': 7.47,
        'Laser Level 2 Money Boost (%)': 15.47,
        'Laser Level 2 Paralyze Probability (%)': 34,
        'Laser Level 3 Damage': 0,
        'Laser Level 3 Base Damage Debuf (%)': 12.4,
        'Laser Level 3 Money Boost (%)': 23.34,
        'Laser Level 3 Explosive Resistance Debuf (%)': 8.01,
        'Laser Level 3 Energy Resistance Debuf (%)': 6,
        'Laser Level 3 Corrosive Damage': 15,
    },
    {
        'Number Of Boost': 6,
        'Laser Level 1 Damage': 0,
        'Laser Level 1 Base Damage Debuf (%)': 4.94,
        'Laser Level 1 Money Boost (%)': 16.37,
        'Laser Level 2 Damage': 0,
        'Laser Level 2 Base Damage Debuf (%)': 7.71,
        'Laser Level 2 Money Boost (%)': 16.37,
        'Laser Level 2 Paralyze Probability (%)': 34.8,
        'Laser Level 3 Damage': 0,
        'Laser Level 3 Base Damage Debuf (%)': 12.62,
        'Laser Level 3 Money Boost (%)': 24.67,
        'Laser Level 3 Explosive Resistance Debuf (%)': 8.28,
        'Laser Level 3 Energy Resistance Debuf (%)': 6.2,
        'Laser Level 3 Corrosive Damage': 18,
    },
    {
        'Number Of Boost': 7,
        'Laser Level 1 Damage': 0,
        'Laser Level 1 Base Damage Debuf (%)': 5.21,
        'Laser Level 1 Money Boost (%)': 17.26,
        'Laser Level 2 Damage': 0,
        'Laser Level 2 Base Damage Debuf (%)': 7.94,
        'Laser Level 2 Money Boost (%)': 17.26,
        'Laser Level 2 Paralyze Probability (%)': 35.6,
        'Laser Level 3 Damage': 0,
        'Laser Level 3 Base Damage Debuf (%)': 12.83,
        'Laser Level 3 Money Boost (%)': 26.01,
        'Laser Level 3 Explosive Resistance Debuf (%)': 8.54,
        'Laser Level 3 Energy Resistance Debuf (%)': 6.4,
        'Laser Level 3 Corrosive Damage': 21,
    },
    {
        'Number Of Boost': 8,
        'Laser Level 1 Damage': 0,
        'Laser Level 1 Base Damage Debuf (%)': 5.48,
        'Laser Level 1 Money Boost (%)': 18.15,
        'Laser Level 2 Damage': 0,
        'Laser Level 2 Base Damage Debuf (%)': 8.18,
        'Laser Level 2 Money Boost (%)': 18.15,
        'Laser Level 2 Paralyze Probability (%)': 36.4,
        'Laser Level 3 Damage': 0,
        'Laser Level 3 Base Damage Debuf (%)': 13.04,
        'Laser Level 3 Money Boost (%)': 27.34,
        'Laser Level 3 Explosive Resistance Debuf (%)': 8.81,
        'Laser Level 3 Energy Resistance Debuf (%)': 6.6,
        'Laser Level 3 Corrosive Damage': 24,
    },
    {
        'Number Of Boost': 9,
        'Laser Level 1 Damage': 0,
        'Laser Level 1 Base Damage Debuf (%)': 5.74,
        'Laser Level 1 Money Boost (%)': 19.05,
        'Laser Level 2 Damage': 0,
        'Laser Level 2 Base Damage Debuf (%)': 8.42,
        'Laser Level 2 Money Boost (%)': 19.05,
        'Laser Level 2 Paralyze Probability (%)': 37.2,
        'Laser Level 3 Damage': 0,
        'Laser Level 3 Base Damage Debuf (%)': 13.26,
        'Laser Level 3 Money Boost (%)': 28.67,
        'Laser Level 3 Explosive Resistance Debuf (%)': 9.08,
        'Laser Level 3 Energy Resistance Debuf (%)': 6.8,
        'Laser Level 3 Corrosive Damage': 27,
    },
    {
        'Number Of Boost': 10,
        'Laser Level 1 Damage': 0,
        'Laser Level 1 Base Damage Debuf (%)': 6.01,
        'Laser Level 1 Money Boost (%)': 19.94,
        'Laser Level 2 Damage': 0,
        'Laser Level 2 Base Damage Debuf (%)': 8.66,
        'Laser Level 2 Money Boost (%)': 19.94,
        'Laser Level 2 Paralyze Probability (%)': 38,
        'Laser Level 3 Damage': 0,
        'Laser Level 3 Base Damage Debuf (%)': 13.47,
        'Laser Level 3 Money Boost (%)': 30.01,
        'Laser Level 3 Explosive Resistance Debuf (%)': 9.34,
        'Laser Level 3 Energy Resistance Debuf (%)': 7,
        'Laser Level 3 Corrosive Damage': 30,
    },
    {
        'Number Of Boost': 11,
        'Laser Level 1 Damage': 0,
        'Laser Level 1 Base Damage Debuf (%)': 6.28,
        'Laser Level 1 Money Boost (%)': 20.83,
        'Laser Level 2 Damage': 0,
        'Laser Level 2 Base Damage Debuf (%)': 8.89,
        'Laser Level 2 Money Boost (%)': 20.83,
        'Laser Level 2 Paralyze Probability (%)': 38.8,
        'Laser Level 3 Damage': 0,
        'Laser Level 3 Base Damage Debuf (%)': 13.68,
        'Laser Level 3 Money Boost (%)': 31.34,
        'Laser Level 3 Explosive Resistance Debuf (%)': 9.61,
        'Laser Level 3 Energy Resistance Debuf (%)': 7.2,
        'Laser Level 3 Corrosive Damage': 33,
    },
    {
        'Number Of Boost': 12,
        'Laser Level 1 Damage': 0,
        'Laser Level 1 Base Damage Debuf (%)': 6.54,
        'Laser Level 1 Money Boost (%)': 21.73,
        'Laser Level 2 Damage': 0,
        'Laser Level 2 Base Damage Debuf (%)': 9.13,
        'Laser Level 2 Money Boost (%)': 21.73,
        'Laser Level 2 Paralyze Probability (%)': 39.6,
        'Laser Level 3 Damage': 0,
        'Laser Level 3 Base Damage Debuf (%)': 13.89,
        'Laser Level 3 Money Boost (%)': 32.67,
        'Laser Level 3 Explosive Resistance Debuf (%)': 9.88,
        'Laser Level 3 Energy Resistance Debuf (%)': 7.4,
        'Laser Level 3 Corrosive Damage': 36,
    },
    {
        'Number Of Boost': 13,
        'Laser Level 1 Damage': 0,
        'Laser Level 1 Base Damage Debuf (%)': 6.81,
        'Laser Level 1 Money Boost (%)': 22.62,
        'Laser Level 2 Damage': 0,
        'Laser Level 2 Base Damage Debuf (%)': 9.37,
        'Laser Level 2 Money Boost (%)': 22.62,
        'Laser Level 2 Paralyze Probability (%)': 40.4,
        'Laser Level 3 Damage': 0,
        'Laser Level 3 Base Damage Debuf (%)': 14.11,
        'Laser Level 3 Money Boost (%)': 34.01,
        'Laser Level 3 Explosive Resistance Debuf (%)': 10.14,
        'Laser Level 3 Energy Resistance Debuf (%)': 7.6,
        'Laser Level 3 Corrosive Damage': 39,
    },
    {
        'Number Of Boost': 14,
        'Laser Level 1 Damage': 0,
        'Laser Level 1 Base Damage Debuf (%)': 7.07,
        'Laser Level 1 Money Boost (%)': 23.52,
        'Laser Level 2 Damage': 0,
        'Laser Level 2 Base Damage Debuf (%)': 9.61,
        'Laser Level 2 Money Boost (%)': 23.52,
        'Laser Level 2 Paralyze Probability (%)': 41.2,
        'Laser Level 3 Damage': 0,
        'Laser Level 3 Base Damage Debuf (%)': 14.32,
        'Laser Level 3 Money Boost (%)': 35.34,
        'Laser Level 3 Explosive Resistance Debuf (%)': 10.41,
        'Laser Level 3 Energy Resistance Debuf (%)': 7.8,
        'Laser Level 3 Corrosive Damage': 42,
    },
    {
        'Number Of Boost': 15,
        'Laser Level 1 Damage': 0,
        'Laser Level 1 Base Damage Debuf (%)': 7.34,
        'Laser Level 1 Money Boost (%)': 24.41,
        'Laser Level 2 Damage': 0,
        'Laser Level 2 Base Damage Debuf (%)': 9.85,
        'Laser Level 2 Money Boost (%)': 24.41,
        'Laser Level 2 Paralyze Probability (%)': 42,
        'Laser Level 3 Damage': 0,
        'Laser Level 3 Base Damage Debuf (%)': 14.53,
        'Laser Level 3 Money Boost (%)': 36.67,
        'Laser Level 3 Explosive Resistance Debuf (%)': 10.68,
        'Laser Level 3 Energy Resistance Debuf (%)': 8,
        'Laser Level 3 Corrosive Damage': 45,
    },
    {
        'Number Of Boost': 16,
        'Laser Level 1 Damage': 0,
        'Laser Level 1 Base Damage Debuf (%)': 7.61,
        'Laser Level 1 Money Boost (%)': 25.3,
        'Laser Level 2 Damage': 0,
        'Laser Level 2 Base Damage Debuf (%)': 10.08,
        'Laser Level 2 Money Boost (%)': 25.3,
        'Laser Level 2 Paralyze Probability (%)': 42.8,
        'Laser Level 3 Damage': 0,
        'Laser Level 3 Base Damage Debuf (%)': 14.75,
        'Laser Level 3 Money Boost (%)': 38.01,
        'Laser Level 3 Explosive Resistance Debuf (%)': 10.94,
        'Laser Level 3 Energy Resistance Debuf (%)': 8.2,
        'Laser Level 3 Corrosive Damage': 48,
    },
    {
        'Number Of Boost': 17,
        'Laser Level 1 Damage': 0,
        'Laser Level 1 Base Damage Debuf (%)': 7.87,
        'Laser Level 1 Money Boost (%)': 26.2,
        'Laser Level 2 Damage': 0,
        'Laser Level 2 Base Damage Debuf (%)': 10.32,
        'Laser Level 2 Money Boost (%)': 26.2,
        'Laser Level 2 Paralyze Probability (%)': 43.6,
        'Laser Level 3 Damage': 0,
        'Laser Level 3 Base Damage Debuf (%)': 14.96,
        'Laser Level 3 Money Boost (%)': 39.34,
        'Laser Level 3 Explosive Resistance Debuf (%)': 11.21,
        'Laser Level 3 Energy Resistance Debuf (%)': 8.4,
        'Laser Level 3 Corrosive Damage': 51,
    },
    {
        'Number Of Boost': 18,
        'Laser Level 1 Damage': 0,
        'Laser Level 1 Base Damage Debuf (%)': 8.14,
        'Laser Level 1 Money Boost (%)': 27.09,
        'Laser Level 2 Damage': 0,
        'Laser Level 2 Base Damage Debuf (%)': 10.56,
        'Laser Level 2 Money Boost (%)': 27.09,
        'Laser Level 2 Paralyze Probability (%)': 44.4,
        'Laser Level 3 Damage': 0,
        'Laser Level 3 Base Damage Debuf (%)': 15.17,
        'Laser Level 3 Money Boost (%)': 40.67,
        'Laser Level 3 Explosive Resistance Debuf (%)': 11.48,
        'Laser Level 3 Energy Resistance Debuf (%)': 8.6,
        'Laser Level 3 Corrosive Damage': 54,
    },
    {
        'Number Of Boost': 19,
        'Laser Level 1 Damage': 0,
        'Laser Level 1 Base Damage Debuf (%)': 8.41,
        'Laser Level 1 Money Boost (%)': 27.98,
        'Laser Level 2 Damage': 0,
        'Laser Level 2 Base Damage Debuf (%)': 10.8,
        'Laser Level 2 Money Boost (%)': 27.98,
        'Laser Level 2 Paralyze Probability (%)': 45.2,
        'Laser Level 3 Damage': 0,
        'Laser Level 3 Base Damage Debuf (%)': 15.39,
        'Laser Level 3 Money Boost (%)': 42.01,
        'Laser Level 3 Explosive Resistance Debuf (%)': 11.74,
        'Laser Level 3 Energy Resistance Debuf (%)': 8.8,
        'Laser Level 3 Corrosive Damage': 57,
    },
    {
        'Number Of Boost': 20,
        'Laser Level 1 Damage': 0,
        'Laser Level 1 Base Damage Debuf (%)': 8.67,
        'Laser Level 1 Money Boost (%)': 28.88,
        'Laser Level 2 Damage': 0,
        'Laser Level 2 Base Damage Debuf (%)': 11.04,
        'Laser Level 2 Money Boost (%)': 28.88,
        'Laser Level 2 Paralyze Probability (%)': 46,
        'Laser Level 3 Damage': 0,
        'Laser Level 3 Base Damage Debuf (%)': 15.6,
        'Laser Level 3 Money Boost (%)': 43.34,
        'Laser Level 3 Explosive Resistance Debuf (%)': 12.01,
        'Laser Level 3 Energy Resistance Debuf (%)': 9,
        'Laser Level 3 Corrosive Damage': 60,
    },
    {
        'Number Of Boost': 21,
        'Laser Level 1 Damage': 0,
        'Laser Level 1 Base Damage Debuf (%)': 8.94,
        'Laser Level 1 Money Boost (%)': 29.77,
        'Laser Level 2 Damage': 0,
        'Laser Level 2 Base Damage Debuf (%)': 11.28,
        'Laser Level 2 Money Boost (%)': 29.77,
        'Laser Level 2 Paralyze Probability (%)': 46.8,
        'Laser Level 3 Damage': 0,
        'Laser Level 3 Base Damage Debuf (%)': 15.81,
        'Laser Level 3 Money Boost (%)': 44.67,
        'Laser Level 3 Explosive Resistance Debuf (%)': 12.28,
        'Laser Level 3 Energy Resistance Debuf (%)': 9.2,
        'Laser Level 3 Corrosive Damage': 63,
    },
    {
        'Number Of Boost': 22,
        'Laser Level 1 Damage': 0,
        'Laser Level 1 Base Damage Debuf (%)': 9.21,
        'Laser Level 1 Money Boost (%)': 30.66,
        'Laser Level 2 Damage': 0,
        'Laser Level 2 Base Damage Debuf (%)': 11.51,
        'Laser Level 2 Money Boost (%)': 30.66,
        'Laser Level 2 Paralyze Probability (%)': 47.6,
        'Laser Level 3 Damage': 0,
        'Laser Level 3 Base Damage Debuf (%)': 16.03,
        'Laser Level 3 Money Boost (%)': 46.01,
        'Laser Level 3 Explosive Resistance Debuf (%)': 12.54,
        'Laser Level 3 Energy Resistance Debuf (%)': 9.4,
        'Laser Level 3 Corrosive Damage': 66,
    },
    {
        'Number Of Boost': 23,
        'Laser Level 1 Damage': 0,
        'Laser Level 1 Base Damage Debuf (%)': 9.47,
        'Laser Level 1 Money Boost (%)': 31.56,
        'Laser Level 2 Damage': 0,
        'Laser Level 2 Base Damage Debuf (%)': 11.75,
        'Laser Level 2 Money Boost (%)': 31.56,
        'Laser Level 2 Paralyze Probability (%)': 48.4,
        'Laser Level 3 Damage': 0,
        'Laser Level 3 Base Damage Debuf (%)': 16.24,
        'Laser Level 3 Money Boost (%)': 47.34,
        'Laser Level 3 Explosive Resistance Debuf (%)': 12.81,
        'Laser Level 3 Energy Resistance Debuf (%)': 9.6,
        'Laser Level 3 Corrosive Damage': 69,
    },
    {
        'Number Of Boost': 24,
        'Laser Level 1 Damage': 0,
        'Laser Level 1 Base Damage Debuf (%)': 9.74,
        'Laser Level 1 Money Boost (%)': 32.45,
        'Laser Level 2 Damage': 0,
        'Laser Level 2 Base Damage Debuf (%)': 11.99,
        'Laser Level 2 Money Boost (%)': 32.45,
        'Laser Level 2 Paralyze Probability (%)': 49.2,
        'Laser Level 3 Damage': 0,
        'Laser Level 3 Base Damage Debuf (%)': 16.45,
        'Laser Level 3 Money Boost (%)': 48.67,
        'Laser Level 3 Explosive Resistance Debuf (%)': 13.08,
        'Laser Level 3 Energy Resistance Debuf (%)': 9.8,
        'Laser Level 3 Corrosive Damage': 72,
    },
    {
        'Number Of Boost': 25,
        'Laser Level 1 Damage': 0,
        'Laser Level 1 Base Damage Debuf (%)': 10,
        'Laser Level 1 Money Boost (%)': 33.34,
        'Laser Level 2 Damage': 0,
        'Laser Level 2 Base Damage Debuf (%)': 10,
        'Laser Level 2 Money Boost (%)': 33.34,
        'Laser Level 2 Paralyze Probability (%)': 50,
        'Laser Level 3 Damage': 0,
        'Laser Level 3 Base Damage Debuf (%)': 10,
        'Laser Level 3 Money Boost (%)': 50,
        'Laser Level 3 Explosive Resistance Debuf (%)': 13.34,
        'Laser Level 3 Energy Resistance Debuf (%)': 10,
        'Laser Level 3 Corrosive Damage': 75,
    },
] as const;
