export const BigDiamondEnemyStats = [
    {
        'Round Tier': 1,
        'Number of Shots Needed To Destroy Player': 4,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 260,
        'Attack Speed': 0.3,
        'Enemies Lifepoints': 241,
        'Tier 3 Frame Speed (Number Frames to HalfScreen Distance)': 150,
    },
    {
        'Round Tier': 2,
        'Number of Shots Needed To Destroy Player': 4,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 260,
        'Attack Speed': 0.3,
        'Enemies Lifepoints': 626,
        'Tier 3 Frame Speed (Number Frames to HalfScreen Distance)': 147.6,
    },
    {
        'Round Tier': 3,
        'Number of Shots Needed To Destroy Player': 4,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 260,
        'Attack Speed': 0.3,
        'Enemies Lifepoints': 1156,
        'Tier 3 Frame Speed (Number Frames to HalfScreen Distance)': 146.4,
    },
    {
        'Round Tier': 4,
        'Number of Shots Needed To Destroy Player': 4,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 260,
        'Attack Speed': 0.3,
        'Enemies Lifepoints': 1831,
        'Tier 3 Frame Speed (Number Frames to HalfScreen Distance)': 145.2,
    },
    {
        'Round Tier': 5,
        'Number of Shots Needed To Destroy Player': 4,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 260,
        'Attack Speed': 0.3,
        'Enemies Lifepoints': 2650,
        'Tier 3 Frame Speed (Number Frames to HalfScreen Distance)': 144,
    },
    {
        'Round Tier': 6,
        'Number of Shots Needed To Destroy Player': 4,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 260,
        'Attack Speed': 0.3,
        'Enemies Lifepoints': 3613,
        'Tier 3 Frame Speed (Number Frames to HalfScreen Distance)': 142.8,
    },
    {
        'Round Tier': 7,
        'Number of Shots Needed To Destroy Player': 3,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 260,
        'Attack Speed': 0.3,
        'Enemies Lifepoints': 4721,
        'Tier 3 Frame Speed (Number Frames to HalfScreen Distance)': 141.6,
    },
    {
        'Round Tier': 8,
        'Number of Shots Needed To Destroy Player': 3,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 260,
        'Attack Speed': 0.3,
        'Enemies Lifepoints': 5974,
        'Tier 3 Frame Speed (Number Frames to HalfScreen Distance)': 140.4,
    },
    {
        'Round Tier': 9,
        'Number of Shots Needed To Destroy Player': 3,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 260,
        'Attack Speed': 0.3,
        'Enemies Lifepoints': 7371,
        'Tier 3 Frame Speed (Number Frames to HalfScreen Distance)': 139.2,
    },
    {
        'Round Tier': 10,
        'Number of Shots Needed To Destroy Player': 3,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 260,
        'Attack Speed': 0.3,
        'Enemies Lifepoints': 8913,
        'Tier 3 Frame Speed (Number Frames to HalfScreen Distance)': 138,
    },
    {
        'Round Tier': 11,
        'Number of Shots Needed To Destroy Player': 3,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 260,
        'Attack Speed': 0.3,
        'Enemies Lifepoints': 10599,
        'Tier 3 Frame Speed (Number Frames to HalfScreen Distance)': 136.8,
    },
    {
        'Round Tier': 12,
        'Number of Shots Needed To Destroy Player': 3,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 260,
        'Attack Speed': 0.3,
        'Enemies Lifepoints': 12429,
        'Tier 3 Frame Speed (Number Frames to HalfScreen Distance)': 135.6,
    },
    {
        'Round Tier': 13,
        'Number of Shots Needed To Destroy Player': 3,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 260,
        'Attack Speed': 0.3,
        'Enemies Lifepoints': 14405,
        'Tier 3 Frame Speed (Number Frames to HalfScreen Distance)': 134.4,
    },
    {
        'Round Tier': 14,
        'Number of Shots Needed To Destroy Player': 3,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 260,
        'Attack Speed': 0.3,
        'Enemies Lifepoints': 16524,
        'Tier 3 Frame Speed (Number Frames to HalfScreen Distance)': 133.2,
    },
    {
        'Round Tier': 15,
        'Number of Shots Needed To Destroy Player': 3,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 260,
        'Attack Speed': 0.3,
        'Enemies Lifepoints': 18789,
        'Tier 3 Frame Speed (Number Frames to HalfScreen Distance)': 132,
    },
    {
        'Round Tier': 16,
        'Number of Shots Needed To Destroy Player': 3,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 260,
        'Attack Speed': 0.3,
        'Enemies Lifepoints': 21197,
        'Tier 3 Frame Speed (Number Frames to HalfScreen Distance)': 130.8,
    },
    {
        'Round Tier': 17,
        'Number of Shots Needed To Destroy Player': 3,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 260,
        'Attack Speed': 0.3,
        'Enemies Lifepoints': 23751,
        'Tier 3 Frame Speed (Number Frames to HalfScreen Distance)': 129.6,
    },
    {
        'Round Tier': 18,
        'Number of Shots Needed To Destroy Player': 3,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 260,
        'Attack Speed': 0.3,
        'Enemies Lifepoints': 26449,
        'Tier 3 Frame Speed (Number Frames to HalfScreen Distance)': 128.4,
    },
    {
        'Round Tier': 19,
        'Number of Shots Needed To Destroy Player': 2,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 260,
        'Attack Speed': 0.3,
        'Enemies Lifepoints': 29291,
        'Tier 3 Frame Speed (Number Frames to HalfScreen Distance)': 127.2,
    },
    {
        'Round Tier': 20,
        'Number of Shots Needed To Destroy Player': 2,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 260,
        'Attack Speed': 0.3,
        'Enemies Lifepoints': 32278,
        'Tier 3 Frame Speed (Number Frames to HalfScreen Distance)': 126,
    },
    {
        'Round Tier': 21,
        'Number of Shots Needed To Destroy Player': 2,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 260,
        'Attack Speed': 0.3,
        'Enemies Lifepoints': 35409,
        'Tier 3 Frame Speed (Number Frames to HalfScreen Distance)': 124.8,
    },
    {
        'Round Tier': 22,
        'Number of Shots Needed To Destroy Player': 2,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 260,
        'Attack Speed': 0.3,
        'Enemies Lifepoints': 38685,
        'Tier 3 Frame Speed (Number Frames to HalfScreen Distance)': 123.6,
    },
    {
        'Round Tier': 23,
        'Number of Shots Needed To Destroy Player': 2,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 260,
        'Attack Speed': 0.3,
        'Enemies Lifepoints': 42106,
        'Tier 3 Frame Speed (Number Frames to HalfScreen Distance)': 122.4,
    },
    {
        'Round Tier': 24,
        'Number of Shots Needed To Destroy Player': 2,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 260,
        'Attack Speed': 0.3,
        'Enemies Lifepoints': 45671,
        'Tier 3 Frame Speed (Number Frames to HalfScreen Distance)': 121.2,
    },
    {
        'Round Tier': 25,
        'Number of Shots Needed To Destroy Player': 2,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 260,
        'Attack Speed': 0.3,
        'Enemies Lifepoints': 49381,
        'Tier 3 Frame Speed (Number Frames to HalfScreen Distance)': 120,
    },
] as const;

export default BigDiamondEnemyStats;
