export const BigDiamondEnemyStats = [
    {
        'Round Tier': 1,
        'Number of Shots Needed To Destroy Player': 4,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 260,
        'Attack Speed': 0.3,
        'Enemies Lifepoints': 161,
        'Tier 3 Frame Speed (Number Frames to HalfScreen Distance)': 150,
    },
    {
        'Round Tier': 2,
        'Number of Shots Needed To Destroy Player': 4,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 260,
        'Attack Speed': 0.3,
        'Enemies Lifepoints': 418,
        'Tier 3 Frame Speed (Number Frames to HalfScreen Distance)': 147.6,
    },
    {
        'Round Tier': 3,
        'Number of Shots Needed To Destroy Player': 4,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 260,
        'Attack Speed': 0.3,
        'Enemies Lifepoints': 771,
        'Tier 3 Frame Speed (Number Frames to HalfScreen Distance)': 146.4,
    },
    {
        'Round Tier': 4,
        'Number of Shots Needed To Destroy Player': 4,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 260,
        'Attack Speed': 0.3,
        'Enemies Lifepoints': 1220,
        'Tier 3 Frame Speed (Number Frames to HalfScreen Distance)': 145.2,
    },
    {
        'Round Tier': 5,
        'Number of Shots Needed To Destroy Player': 4,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 260,
        'Attack Speed': 0.3,
        'Enemies Lifepoints': 1766,
        'Tier 3 Frame Speed (Number Frames to HalfScreen Distance)': 144,
    },
    {
        'Round Tier': 6,
        'Number of Shots Needed To Destroy Player': 4,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 260,
        'Attack Speed': 0.3,
        'Enemies Lifepoints': 2409,
        'Tier 3 Frame Speed (Number Frames to HalfScreen Distance)': 142.8,
    },
    {
        'Round Tier': 7,
        'Number of Shots Needed To Destroy Player': 3,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 260,
        'Attack Speed': 0.3,
        'Enemies Lifepoints': 3148,
        'Tier 3 Frame Speed (Number Frames to HalfScreen Distance)': 141.6,
    },
    {
        'Round Tier': 8,
        'Number of Shots Needed To Destroy Player': 3,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 260,
        'Attack Speed': 0.3,
        'Enemies Lifepoints': 3983,
        'Tier 3 Frame Speed (Number Frames to HalfScreen Distance)': 140.4,
    },
    {
        'Round Tier': 9,
        'Number of Shots Needed To Destroy Player': 3,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 260,
        'Attack Speed': 0.3,
        'Enemies Lifepoints': 4914,
        'Tier 3 Frame Speed (Number Frames to HalfScreen Distance)': 139.2,
    },
    {
        'Round Tier': 10,
        'Number of Shots Needed To Destroy Player': 3,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 260,
        'Attack Speed': 0.3,
        'Enemies Lifepoints': 5942,
        'Tier 3 Frame Speed (Number Frames to HalfScreen Distance)': 138,
    },
    {
        'Round Tier': 11,
        'Number of Shots Needed To Destroy Player': 3,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 260,
        'Attack Speed': 0.3,
        'Enemies Lifepoints': 7066,
        'Tier 3 Frame Speed (Number Frames to HalfScreen Distance)': 136.8,
    },
    {
        'Round Tier': 12,
        'Number of Shots Needed To Destroy Player': 3,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 260,
        'Attack Speed': 0.3,
        'Enemies Lifepoints': 8286,
        'Tier 3 Frame Speed (Number Frames to HalfScreen Distance)': 135.6,
    },
    {
        'Round Tier': 13,
        'Number of Shots Needed To Destroy Player': 3,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 260,
        'Attack Speed': 0.3,
        'Enemies Lifepoints': 9603,
        'Tier 3 Frame Speed (Number Frames to HalfScreen Distance)': 134.4,
    },
    {
        'Round Tier': 14,
        'Number of Shots Needed To Destroy Player': 3,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 260,
        'Attack Speed': 0.3,
        'Enemies Lifepoints': 11016,
        'Tier 3 Frame Speed (Number Frames to HalfScreen Distance)': 133.2,
    },
    {
        'Round Tier': 15,
        'Number of Shots Needed To Destroy Player': 3,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 260,
        'Attack Speed': 0.3,
        'Enemies Lifepoints': 12526,
        'Tier 3 Frame Speed (Number Frames to HalfScreen Distance)': 132,
    },
    {
        'Round Tier': 16,
        'Number of Shots Needed To Destroy Player': 3,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 260,
        'Attack Speed': 0.3,
        'Enemies Lifepoints': 14132,
        'Tier 3 Frame Speed (Number Frames to HalfScreen Distance)': 130.8,
    },
    {
        'Round Tier': 17,
        'Number of Shots Needed To Destroy Player': 3,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 260,
        'Attack Speed': 0.3,
        'Enemies Lifepoints': 15834,
        'Tier 3 Frame Speed (Number Frames to HalfScreen Distance)': 129.6,
    },
    {
        'Round Tier': 18,
        'Number of Shots Needed To Destroy Player': 3,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 260,
        'Attack Speed': 0.3,
        'Enemies Lifepoints': 17632,
        'Tier 3 Frame Speed (Number Frames to HalfScreen Distance)': 128.4,
    },
    {
        'Round Tier': 19,
        'Number of Shots Needed To Destroy Player': 2,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 260,
        'Attack Speed': 0.3,
        'Enemies Lifepoints': 19527,
        'Tier 3 Frame Speed (Number Frames to HalfScreen Distance)': 127.2,
    },
    {
        'Round Tier': 20,
        'Number of Shots Needed To Destroy Player': 2,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 260,
        'Attack Speed': 0.3,
        'Enemies Lifepoints': 21519,
        'Tier 3 Frame Speed (Number Frames to HalfScreen Distance)': 126,
    },
    {
        'Round Tier': 21,
        'Number of Shots Needed To Destroy Player': 2,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 260,
        'Attack Speed': 0.3,
        'Enemies Lifepoints': 23606,
        'Tier 3 Frame Speed (Number Frames to HalfScreen Distance)': 124.8,
    },
    {
        'Round Tier': 22,
        'Number of Shots Needed To Destroy Player': 2,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 260,
        'Attack Speed': 0.3,
        'Enemies Lifepoints': 25790,
        'Tier 3 Frame Speed (Number Frames to HalfScreen Distance)': 123.6,
    },
    {
        'Round Tier': 23,
        'Number of Shots Needed To Destroy Player': 2,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 260,
        'Attack Speed': 0.3,
        'Enemies Lifepoints': 28071,
        'Tier 3 Frame Speed (Number Frames to HalfScreen Distance)': 122.4,
    },
    {
        'Round Tier': 24,
        'Number of Shots Needed To Destroy Player': 2,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 260,
        'Attack Speed': 0.3,
        'Enemies Lifepoints': 30447,
        'Tier 3 Frame Speed (Number Frames to HalfScreen Distance)': 121.2,
    },
    {
        'Round Tier': 25,
        'Number of Shots Needed To Destroy Player': 2,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 260,
        'Attack Speed': 0.3,
        'Enemies Lifepoints': 32920,
        'Tier 3 Frame Speed (Number Frames to HalfScreen Distance)': 120,
    },
] as const;

export default BigDiamondEnemyStats;
