export const BladeConstant = [
    {
        'Skill Name': 'Blade',
        Level: 1,
        'Skill Price': 1000,
        'Projectile Speed': 75,
        'Hit Rate Per Second': 5,
        'Damage Increase': 0,
        'Primary Skill': 'Energy',
        'Secondary Skill': null,
    },
    {
        'Skill Name': 'Blade',
        Level: 2,
        'Skill Price': 6300,
        'Projectile Speed': 75,
        'Hit Rate Per Second': 5,
        'Damage Increase': 0,
        'Primary Skill': 'Energy',
        'Secondary Skill': null,
    },
    {
        'Skill Name': 'Blade',
        Level: 3,
        'Skill Price': 20000,
        'Projectile Speed': 75,
        'Hit Rate Per Second': 5,
        'Damage Increase': 1.25,
        'Primary Skill': 'Energy',
        'Secondary Skill': null,
    },
] as const;
