export const MediumDiamondEnemyStats = [
    {
        'Round Tier': 1,
        'Number of Shots Needed To Destroy Player': 6,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 240,
        'Attack Speed': 0.4,
        'Enemies Lifepoints': 80,
        'Tier 2 Frame Speed (Number Frames to HalfScreen Distance)': 130,
    },
    {
        'Round Tier': 2,
        'Number of Shots Needed To Destroy Player': 6,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 240,
        'Attack Speed': 0.4,
        'Enemies Lifepoints': 209,
        'Tier 2 Frame Speed (Number Frames to HalfScreen Distance)': 127.6,
    },
    {
        'Round Tier': 3,
        'Number of Shots Needed To Destroy Player': 6,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 240,
        'Attack Speed': 0.4,
        'Enemies Lifepoints': 385,
        'Tier 2 Frame Speed (Number Frames to HalfScreen Distance)': 126.4,
    },
    {
        'Round Tier': 4,
        'Number of Shots Needed To Destroy Player': 6,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 240,
        'Attack Speed': 0.4,
        'Enemies Lifepoints': 610,
        'Tier 2 Frame Speed (Number Frames to HalfScreen Distance)': 125.2,
    },
    {
        'Round Tier': 5,
        'Number of Shots Needed To Destroy Player': 6,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 240,
        'Attack Speed': 0.4,
        'Enemies Lifepoints': 883,
        'Tier 2 Frame Speed (Number Frames to HalfScreen Distance)': 124,
    },
    {
        'Round Tier': 6,
        'Number of Shots Needed To Destroy Player': 6,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 240,
        'Attack Speed': 0.4,
        'Enemies Lifepoints': 1204,
        'Tier 2 Frame Speed (Number Frames to HalfScreen Distance)': 122.8,
    },
    {
        'Round Tier': 7,
        'Number of Shots Needed To Destroy Player': 5,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 240,
        'Attack Speed': 0.4,
        'Enemies Lifepoints': 1574,
        'Tier 2 Frame Speed (Number Frames to HalfScreen Distance)': 121.6,
    },
    {
        'Round Tier': 8,
        'Number of Shots Needed To Destroy Player': 5,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 240,
        'Attack Speed': 0.4,
        'Enemies Lifepoints': 1991,
        'Tier 2 Frame Speed (Number Frames to HalfScreen Distance)': 120.4,
    },
    {
        'Round Tier': 9,
        'Number of Shots Needed To Destroy Player': 5,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 240,
        'Attack Speed': 0.4,
        'Enemies Lifepoints': 2457,
        'Tier 2 Frame Speed (Number Frames to HalfScreen Distance)': 119.2,
    },
    {
        'Round Tier': 10,
        'Number of Shots Needed To Destroy Player': 5,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 240,
        'Attack Speed': 0.4,
        'Enemies Lifepoints': 2971,
        'Tier 2 Frame Speed (Number Frames to HalfScreen Distance)': 118,
    },
    {
        'Round Tier': 11,
        'Number of Shots Needed To Destroy Player': 5,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 240,
        'Attack Speed': 0.4,
        'Enemies Lifepoints': 3533,
        'Tier 2 Frame Speed (Number Frames to HalfScreen Distance)': 116.8,
    },
    {
        'Round Tier': 12,
        'Number of Shots Needed To Destroy Player': 5,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 240,
        'Attack Speed': 0.4,
        'Enemies Lifepoints': 4143,
        'Tier 2 Frame Speed (Number Frames to HalfScreen Distance)': 115.6,
    },
    {
        'Round Tier': 13,
        'Number of Shots Needed To Destroy Player': 5,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 240,
        'Attack Speed': 0.4,
        'Enemies Lifepoints': 4802,
        'Tier 2 Frame Speed (Number Frames to HalfScreen Distance)': 114.4,
    },
    {
        'Round Tier': 14,
        'Number of Shots Needed To Destroy Player': 5,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 240,
        'Attack Speed': 0.4,
        'Enemies Lifepoints': 5508,
        'Tier 2 Frame Speed (Number Frames to HalfScreen Distance)': 113.2,
    },
    {
        'Round Tier': 15,
        'Number of Shots Needed To Destroy Player': 5,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 240,
        'Attack Speed': 0.4,
        'Enemies Lifepoints': 6263,
        'Tier 2 Frame Speed (Number Frames to HalfScreen Distance)': 112,
    },
    {
        'Round Tier': 16,
        'Number of Shots Needed To Destroy Player': 5,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 240,
        'Attack Speed': 0.4,
        'Enemies Lifepoints': 7066,
        'Tier 2 Frame Speed (Number Frames to HalfScreen Distance)': 110.8,
    },
    {
        'Round Tier': 17,
        'Number of Shots Needed To Destroy Player': 5,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 240,
        'Attack Speed': 0.4,
        'Enemies Lifepoints': 7917,
        'Tier 2 Frame Speed (Number Frames to HalfScreen Distance)': 109.6,
    },
    {
        'Round Tier': 18,
        'Number of Shots Needed To Destroy Player': 5,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 240,
        'Attack Speed': 0.4,
        'Enemies Lifepoints': 8816,
        'Tier 2 Frame Speed (Number Frames to HalfScreen Distance)': 108.4,
    },
    {
        'Round Tier': 19,
        'Number of Shots Needed To Destroy Player': 4,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 240,
        'Attack Speed': 0.4,
        'Enemies Lifepoints': 9764,
        'Tier 2 Frame Speed (Number Frames to HalfScreen Distance)': 107.2,
    },
    {
        'Round Tier': 20,
        'Number of Shots Needed To Destroy Player': 4,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 240,
        'Attack Speed': 0.4,
        'Enemies Lifepoints': 10759,
        'Tier 2 Frame Speed (Number Frames to HalfScreen Distance)': 106,
    },
    {
        'Round Tier': 21,
        'Number of Shots Needed To Destroy Player': 4,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 240,
        'Attack Speed': 0.4,
        'Enemies Lifepoints': 11803,
        'Tier 2 Frame Speed (Number Frames to HalfScreen Distance)': 104.8,
    },
    {
        'Round Tier': 22,
        'Number of Shots Needed To Destroy Player': 4,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 240,
        'Attack Speed': 0.4,
        'Enemies Lifepoints': 12895,
        'Tier 2 Frame Speed (Number Frames to HalfScreen Distance)': 103.6,
    },
    {
        'Round Tier': 23,
        'Number of Shots Needed To Destroy Player': 4,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 240,
        'Attack Speed': 0.4,
        'Enemies Lifepoints': 14035,
        'Tier 2 Frame Speed (Number Frames to HalfScreen Distance)': 102.4,
    },
    {
        'Round Tier': 24,
        'Number of Shots Needed To Destroy Player': 4,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 240,
        'Attack Speed': 0.4,
        'Enemies Lifepoints': 15224,
        'Tier 2 Frame Speed (Number Frames to HalfScreen Distance)': 101.2,
    },
    {
        'Round Tier': 25,
        'Number of Shots Needed To Destroy Player': 4,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 240,
        'Attack Speed': 0.4,
        'Enemies Lifepoints': 16460,
        'Tier 2 Frame Speed (Number Frames to HalfScreen Distance)': 100,
    },
] as const;

export default MediumDiamondEnemyStats;
