export const MediumDiamondEnemyStats = [
    {
        'Round Tier': 1,
        'Number of Shots Needed To Destroy Player': 6,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 240,
        'Attack Speed': 0.4,
        'Enemies Lifepoints': 161,
        'Tier 2 Frame Speed (Number Frames to HalfScreen Distance)': 130,
    },
    {
        'Round Tier': 2,
        'Number of Shots Needed To Destroy Player': 6,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 240,
        'Attack Speed': 0.4,
        'Enemies Lifepoints': 418,
        'Tier 2 Frame Speed (Number Frames to HalfScreen Distance)': 127.6,
    },
    {
        'Round Tier': 3,
        'Number of Shots Needed To Destroy Player': 6,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 240,
        'Attack Speed': 0.4,
        'Enemies Lifepoints': 771,
        'Tier 2 Frame Speed (Number Frames to HalfScreen Distance)': 126.4,
    },
    {
        'Round Tier': 4,
        'Number of Shots Needed To Destroy Player': 6,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 240,
        'Attack Speed': 0.4,
        'Enemies Lifepoints': 1220,
        'Tier 2 Frame Speed (Number Frames to HalfScreen Distance)': 125.2,
    },
    {
        'Round Tier': 5,
        'Number of Shots Needed To Destroy Player': 6,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 240,
        'Attack Speed': 0.4,
        'Enemies Lifepoints': 1766,
        'Tier 2 Frame Speed (Number Frames to HalfScreen Distance)': 124,
    },
    {
        'Round Tier': 6,
        'Number of Shots Needed To Destroy Player': 6,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 240,
        'Attack Speed': 0.4,
        'Enemies Lifepoints': 2409,
        'Tier 2 Frame Speed (Number Frames to HalfScreen Distance)': 122.8,
    },
    {
        'Round Tier': 7,
        'Number of Shots Needed To Destroy Player': 5,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 240,
        'Attack Speed': 0.4,
        'Enemies Lifepoints': 3148,
        'Tier 2 Frame Speed (Number Frames to HalfScreen Distance)': 121.6,
    },
    {
        'Round Tier': 8,
        'Number of Shots Needed To Destroy Player': 5,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 240,
        'Attack Speed': 0.4,
        'Enemies Lifepoints': 3983,
        'Tier 2 Frame Speed (Number Frames to HalfScreen Distance)': 120.4,
    },
    {
        'Round Tier': 9,
        'Number of Shots Needed To Destroy Player': 5,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 240,
        'Attack Speed': 0.4,
        'Enemies Lifepoints': 4914,
        'Tier 2 Frame Speed (Number Frames to HalfScreen Distance)': 119.2,
    },
    {
        'Round Tier': 10,
        'Number of Shots Needed To Destroy Player': 5,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 240,
        'Attack Speed': 0.4,
        'Enemies Lifepoints': 5942,
        'Tier 2 Frame Speed (Number Frames to HalfScreen Distance)': 118,
    },
    {
        'Round Tier': 11,
        'Number of Shots Needed To Destroy Player': 5,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 240,
        'Attack Speed': 0.4,
        'Enemies Lifepoints': 7066,
        'Tier 2 Frame Speed (Number Frames to HalfScreen Distance)': 116.8,
    },
    {
        'Round Tier': 12,
        'Number of Shots Needed To Destroy Player': 5,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 240,
        'Attack Speed': 0.4,
        'Enemies Lifepoints': 8286,
        'Tier 2 Frame Speed (Number Frames to HalfScreen Distance)': 115.6,
    },
    {
        'Round Tier': 13,
        'Number of Shots Needed To Destroy Player': 5,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 240,
        'Attack Speed': 0.4,
        'Enemies Lifepoints': 9603,
        'Tier 2 Frame Speed (Number Frames to HalfScreen Distance)': 114.4,
    },
    {
        'Round Tier': 14,
        'Number of Shots Needed To Destroy Player': 5,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 240,
        'Attack Speed': 0.4,
        'Enemies Lifepoints': 11016,
        'Tier 2 Frame Speed (Number Frames to HalfScreen Distance)': 113.2,
    },
    {
        'Round Tier': 15,
        'Number of Shots Needed To Destroy Player': 5,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 240,
        'Attack Speed': 0.4,
        'Enemies Lifepoints': 12526,
        'Tier 2 Frame Speed (Number Frames to HalfScreen Distance)': 112,
    },
    {
        'Round Tier': 16,
        'Number of Shots Needed To Destroy Player': 5,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 240,
        'Attack Speed': 0.4,
        'Enemies Lifepoints': 14132,
        'Tier 2 Frame Speed (Number Frames to HalfScreen Distance)': 110.8,
    },
    {
        'Round Tier': 17,
        'Number of Shots Needed To Destroy Player': 5,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 240,
        'Attack Speed': 0.4,
        'Enemies Lifepoints': 15834,
        'Tier 2 Frame Speed (Number Frames to HalfScreen Distance)': 109.6,
    },
    {
        'Round Tier': 18,
        'Number of Shots Needed To Destroy Player': 5,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 240,
        'Attack Speed': 0.4,
        'Enemies Lifepoints': 17632,
        'Tier 2 Frame Speed (Number Frames to HalfScreen Distance)': 108.4,
    },
    {
        'Round Tier': 19,
        'Number of Shots Needed To Destroy Player': 4,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 240,
        'Attack Speed': 0.4,
        'Enemies Lifepoints': 19527,
        'Tier 2 Frame Speed (Number Frames to HalfScreen Distance)': 107.2,
    },
    {
        'Round Tier': 20,
        'Number of Shots Needed To Destroy Player': 4,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 240,
        'Attack Speed': 0.4,
        'Enemies Lifepoints': 21519,
        'Tier 2 Frame Speed (Number Frames to HalfScreen Distance)': 106,
    },
    {
        'Round Tier': 21,
        'Number of Shots Needed To Destroy Player': 4,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 240,
        'Attack Speed': 0.4,
        'Enemies Lifepoints': 23606,
        'Tier 2 Frame Speed (Number Frames to HalfScreen Distance)': 104.8,
    },
    {
        'Round Tier': 22,
        'Number of Shots Needed To Destroy Player': 4,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 240,
        'Attack Speed': 0.4,
        'Enemies Lifepoints': 25790,
        'Tier 2 Frame Speed (Number Frames to HalfScreen Distance)': 103.6,
    },
    {
        'Round Tier': 23,
        'Number of Shots Needed To Destroy Player': 4,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 240,
        'Attack Speed': 0.4,
        'Enemies Lifepoints': 28071,
        'Tier 2 Frame Speed (Number Frames to HalfScreen Distance)': 102.4,
    },
    {
        'Round Tier': 24,
        'Number of Shots Needed To Destroy Player': 4,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 240,
        'Attack Speed': 0.4,
        'Enemies Lifepoints': 30447,
        'Tier 2 Frame Speed (Number Frames to HalfScreen Distance)': 101.2,
    },
    {
        'Round Tier': 25,
        'Number of Shots Needed To Destroy Player': 4,
        'Bullet Speed (Number Frames to Cover HalfScreen Distance)': 240,
        'Attack Speed': 0.4,
        'Enemies Lifepoints': 32920,
        'Tier 2 Frame Speed (Number Frames to HalfScreen Distance)': 100,
    },
] as const;

export default MediumDiamondEnemyStats;
