export const MirrorShieldDamage = [
    {
        'Number Of Boost': 0,
        'Thunder Beam Damage': 0.45,
        'Energy Stat': 0,
        'Explosive Entity Damage': 15,
        'Explosive Stat (%)': 0,
    },
    {
        'Number Of Boost': 1,
        'Thunder Beam Damage': 1.25,
        'Energy Stat': 4,
        'Explosive Entity Damage': 15.8,
        'Explosive Stat (%)': 2.4,
    },
    {
        'Number Of Boost': 2,
        'Thunder Beam Damage': 2.05,
        'Energy Stat': 8,
        'Explosive Entity Damage': 16.6,
        'Explosive Stat (%)': 4.8,
    },
    {
        'Number Of Boost': 3,
        'Thunder Beam Damage': 2.85,
        'Energy Stat': 12,
        'Explosive Entity Damage': 17.4,
        'Explosive Stat (%)': 7.2,
    },
    {
        'Number Of Boost': 4,
        'Thunder Beam Damage': 3.65,
        'Energy Stat': 16,
        'Explosive Entity Damage': 18.2,
        'Explosive Stat (%)': 9.6,
    },
    {
        'Number Of Boost': 5,
        'Thunder Beam Damage': 4.45,
        'Energy Stat': 20,
        'Explosive Entity Damage': 19,
        'Explosive Stat (%)': 12,
    },
    {
        'Number Of Boost': 6,
        'Thunder Beam Damage': 5.25,
        'Energy Stat': 24,
        'Explosive Entity Damage': 19.8,
        'Explosive Stat (%)': 14.4,
    },
    {
        'Number Of Boost': 7,
        'Thunder Beam Damage': 6.05,
        'Energy Stat': 28,
        'Explosive Entity Damage': 20.6,
        'Explosive Stat (%)': 16.8,
    },
    {
        'Number Of Boost': 8,
        'Thunder Beam Damage': 6.85,
        'Energy Stat': 32,
        'Explosive Entity Damage': 21.4,
        'Explosive Stat (%)': 19.2,
    },
    {
        'Number Of Boost': 9,
        'Thunder Beam Damage': 7.65,
        'Energy Stat': 36,
        'Explosive Entity Damage': 22.2,
        'Explosive Stat (%)': 21.6,
    },
    {
        'Number Of Boost': 10,
        'Thunder Beam Damage': 8.45,
        'Energy Stat': 40,
        'Explosive Entity Damage': 23,
        'Explosive Stat (%)': 24,
    },
    {
        'Number Of Boost': 11,
        'Thunder Beam Damage': 9.25,
        'Energy Stat': 44,
        'Explosive Entity Damage': 23.8,
        'Explosive Stat (%)': 26.4,
    },
    {
        'Number Of Boost': 12,
        'Thunder Beam Damage': 10.05,
        'Energy Stat': 48,
        'Explosive Entity Damage': 24.6,
        'Explosive Stat (%)': 28.8,
    },
    {
        'Number Of Boost': 13,
        'Thunder Beam Damage': 10.85,
        'Energy Stat': 52,
        'Explosive Entity Damage': 25.4,
        'Explosive Stat (%)': 31.2,
    },
    {
        'Number Of Boost': 14,
        'Thunder Beam Damage': 11.65,
        'Energy Stat': 56,
        'Explosive Entity Damage': 26.2,
        'Explosive Stat (%)': 33.6,
    },
    {
        'Number Of Boost': 15,
        'Thunder Beam Damage': 12.45,
        'Energy Stat': 60,
        'Explosive Entity Damage': 27,
        'Explosive Stat (%)': 36,
    },
    {
        'Number Of Boost': 16,
        'Thunder Beam Damage': 13.25,
        'Energy Stat': 64,
        'Explosive Entity Damage': 27.8,
        'Explosive Stat (%)': 38.4,
    },
    {
        'Number Of Boost': 17,
        'Thunder Beam Damage': 14.05,
        'Energy Stat': 68,
        'Explosive Entity Damage': 28.6,
        'Explosive Stat (%)': 40.8,
    },
    {
        'Number Of Boost': 18,
        'Thunder Beam Damage': 14.85,
        'Energy Stat': 72,
        'Explosive Entity Damage': 29.4,
        'Explosive Stat (%)': 43.2,
    },
    {
        'Number Of Boost': 19,
        'Thunder Beam Damage': 15.65,
        'Energy Stat': 76,
        'Explosive Entity Damage': 30.2,
        'Explosive Stat (%)': 45.6,
    },
    {
        'Number Of Boost': 20,
        'Thunder Beam Damage': 16.45,
        'Energy Stat': 80,
        'Explosive Entity Damage': 31,
        'Explosive Stat (%)': 48,
    },
    {
        'Number Of Boost': 21,
        'Thunder Beam Damage': 17.25,
        'Energy Stat': 84,
        'Explosive Entity Damage': 31.8,
        'Explosive Stat (%)': 50.4,
    },
    {
        'Number Of Boost': 22,
        'Thunder Beam Damage': 18.05,
        'Energy Stat': 88,
        'Explosive Entity Damage': 32.6,
        'Explosive Stat (%)': 52.8,
    },
    {
        'Number Of Boost': 23,
        'Thunder Beam Damage': 18.85,
        'Energy Stat': 92,
        'Explosive Entity Damage': 33.4,
        'Explosive Stat (%)': 55.2,
    },
    {
        'Number Of Boost': 24,
        'Thunder Beam Damage': 19.65,
        'Energy Stat': 96,
        'Explosive Entity Damage': 34.2,
        'Explosive Stat (%)': 57.6,
    },
    {
        'Number Of Boost': 25,
        'Thunder Beam Damage': 20.45,
        'Energy Stat': 100,
        'Explosive Entity Damage': 35,
        'Explosive Stat (%)': 60,
    },
] as const;
