export const PlayerBulletDamageStats = [
    {
        'Number Of Boost': 0,
        'Player Bullet Damage': 30,
        'Player Bullet Attack Speed': 1.5,
        'Projectile Speed': 75,
    },
    {
        'Number Of Boost': 1,
        'Player Bullet Damage': 30.8,
        'Player Bullet Attack Speed': 1.52,
        'Projectile Speed': 75,
    },
    {
        'Number Of Boost': 2,
        'Player Bullet Damage': 31.6,
        'Player Bullet Attack Speed': 1.54,
        'Projectile Speed': 75,
    },
    {
        'Number Of Boost': 3,
        'Player Bullet Damage': 32.4,
        'Player Bullet Attack Speed': 1.56,
        'Projectile Speed': 75,
    },
    {
        'Number Of Boost': 4,
        'Player Bullet Damage': 33.2,
        'Player Bullet Attack Speed': 1.58,
        'Projectile Speed': 75,
    },
    {
        'Number Of Boost': 5,
        'Player Bullet Damage': 34,
        'Player Bullet Attack Speed': 1.6,
        'Projectile Speed': 75,
    },
    {
        'Number Of Boost': 6,
        'Player Bullet Damage': 34.8,
        'Player Bullet Attack Speed': 1.62,
        'Projectile Speed': 75,
    },
    {
        'Number Of Boost': 7,
        'Player Bullet Damage': 35.6,
        'Player Bullet Attack Speed': 1.64,
        'Projectile Speed': 75,
    },
    {
        'Number Of Boost': 8,
        'Player Bullet Damage': 36.4,
        'Player Bullet Attack Speed': 1.66,
        'Projectile Speed': 75,
    },
    {
        'Number Of Boost': 9,
        'Player Bullet Damage': 37.2,
        'Player Bullet Attack Speed': 1.68,
        'Projectile Speed': 60,
    },
    {
        'Number Of Boost': 10,
        'Player Bullet Damage': 38,
        'Player Bullet Attack Speed': 1.7,
        'Projectile Speed': 60,
    },
    {
        'Number Of Boost': 11,
        'Player Bullet Damage': 38.8,
        'Player Bullet Attack Speed': 1.72,
        'Projectile Speed': 60,
    },
    {
        'Number Of Boost': 12,
        'Player Bullet Damage': 39.6,
        'Player Bullet Attack Speed': 1.74,
        'Projectile Speed': 60,
    },
    {
        'Number Of Boost': 13,
        'Player Bullet Damage': 40.4,
        'Player Bullet Attack Speed': 1.76,
        'Projectile Speed': 60,
    },
    {
        'Number Of Boost': 14,
        'Player Bullet Damage': 41.2,
        'Player Bullet Attack Speed': 1.78,
        'Projectile Speed': 60,
    },
    {
        'Number Of Boost': 15,
        'Player Bullet Damage': 42,
        'Player Bullet Attack Speed': 1.8,
        'Projectile Speed': 60,
    },
    {
        'Number Of Boost': 16,
        'Player Bullet Damage': 42.8,
        'Player Bullet Attack Speed': 1.82,
        'Projectile Speed': 60,
    },
    {
        'Number Of Boost': 17,
        'Player Bullet Damage': 43.6,
        'Player Bullet Attack Speed': 1.84,
        'Projectile Speed': 60,
    },
    {
        'Number Of Boost': 18,
        'Player Bullet Damage': 44.4,
        'Player Bullet Attack Speed': 1.86,
        'Projectile Speed': 45,
    },
    {
        'Number Of Boost': 19,
        'Player Bullet Damage': 45.2,
        'Player Bullet Attack Speed': 1.88,
        'Projectile Speed': 45,
    },
    {
        'Number Of Boost': 20,
        'Player Bullet Damage': 46,
        'Player Bullet Attack Speed': 1.9,
        'Projectile Speed': 45,
    },
    {
        'Number Of Boost': 21,
        'Player Bullet Damage': 46.8,
        'Player Bullet Attack Speed': 1.92,
        'Projectile Speed': 45,
    },
    {
        'Number Of Boost': 22,
        'Player Bullet Damage': 47.6,
        'Player Bullet Attack Speed': 1.94,
        'Projectile Speed': 45,
    },
    {
        'Number Of Boost': 23,
        'Player Bullet Damage': 48.4,
        'Player Bullet Attack Speed': 1.96,
        'Projectile Speed': 45,
    },
    {
        'Number Of Boost': 24,
        'Player Bullet Damage': 49.2,
        'Player Bullet Attack Speed': 1.98,
        'Projectile Speed': 45,
    },
    {
        'Number Of Boost': 25,
        'Player Bullet Damage': 50,
        'Player Bullet Attack Speed': 2,
        'Projectile Speed': 45,
    },
] as const;
