export const PlayerStats = [
    {
        'Number of Boosts': 0,
        'Base Health': 100,
        'Speed of the Player (Number Frames to HalfScreen Distance)': 100,
        'Invulnerability Time Period (Seconds)': 1,
    },
    {
        'Number of Boosts': 1,
        'Base Health': 120,
        'Speed of the Player (Number Frames to HalfScreen Distance)': 99.6,
        'Invulnerability Time Period (Seconds)': 1,
    },
    {
        'Number of Boosts': 2,
        'Base Health': 140,
        'Speed of the Player (Number Frames to HalfScreen Distance)': 99.2,
        'Invulnerability Time Period (Seconds)': 1,
    },
    {
        'Number of Boosts': 3,
        'Base Health': 160,
        'Speed of the Player (Number Frames to HalfScreen Distance)': 98.8,
        'Invulnerability Time Period (Seconds)': 1,
    },
    {
        'Number of Boosts': 4,
        'Base Health': 180,
        'Speed of the Player (Number Frames to HalfScreen Distance)': 98.4,
        'Invulnerability Time Period (Seconds)': 1,
    },
    {
        'Number of Boosts': 5,
        'Base Health': 200,
        'Speed of the Player (Number Frames to HalfScreen Distance)': 98,
        'Invulnerability Time Period (Seconds)': 1,
    },
    {
        'Number of Boosts': 6,
        'Base Health': 220,
        'Speed of the Player (Number Frames to HalfScreen Distance)': 97.6,
        'Invulnerability Time Period (Seconds)': 1,
    },
    {
        'Number of Boosts': 7,
        'Base Health': 240,
        'Speed of the Player (Number Frames to HalfScreen Distance)': 97.2,
        'Invulnerability Time Period (Seconds)': 1,
    },
    {
        'Number of Boosts': 8,
        'Base Health': 260,
        'Speed of the Player (Number Frames to HalfScreen Distance)': 96.8,
        'Invulnerability Time Period (Seconds)': 1,
    },
    {
        'Number of Boosts': 9,
        'Base Health': 280,
        'Speed of the Player (Number Frames to HalfScreen Distance)': 96.4,
        'Invulnerability Time Period (Seconds)': 1,
    },
    {
        'Number of Boosts': 10,
        'Base Health': 300,
        'Speed of the Player (Number Frames to HalfScreen Distance)': 96,
        'Invulnerability Time Period (Seconds)': 1,
    },
    {
        'Number of Boosts': 11,
        'Base Health': 320,
        'Speed of the Player (Number Frames to HalfScreen Distance)': 95.6,
        'Invulnerability Time Period (Seconds)': 1,
    },
    {
        'Number of Boosts': 12,
        'Base Health': 340,
        'Speed of the Player (Number Frames to HalfScreen Distance)': 95.2,
        'Invulnerability Time Period (Seconds)': 1,
    },
    {
        'Number of Boosts': 13,
        'Base Health': 360,
        'Speed of the Player (Number Frames to HalfScreen Distance)': 94.8,
        'Invulnerability Time Period (Seconds)': 1,
    },
    {
        'Number of Boosts': 14,
        'Base Health': 380,
        'Speed of the Player (Number Frames to HalfScreen Distance)': 94.4,
        'Invulnerability Time Period (Seconds)': 1,
    },
    {
        'Number of Boosts': 15,
        'Base Health': 400,
        'Speed of the Player (Number Frames to HalfScreen Distance)': 94,
        'Invulnerability Time Period (Seconds)': 1,
    },
    {
        'Number of Boosts': 16,
        'Base Health': 420,
        'Speed of the Player (Number Frames to HalfScreen Distance)': 93.6,
        'Invulnerability Time Period (Seconds)': 1,
    },
    {
        'Number of Boosts': 17,
        'Base Health': 440,
        'Speed of the Player (Number Frames to HalfScreen Distance)': 93.2,
        'Invulnerability Time Period (Seconds)': 1,
    },
    {
        'Number of Boosts': 18,
        'Base Health': 460,
        'Speed of the Player (Number Frames to HalfScreen Distance)': 92.8,
        'Invulnerability Time Period (Seconds)': 1,
    },
    {
        'Number of Boosts': 19,
        'Base Health': 480,
        'Speed of the Player (Number Frames to HalfScreen Distance)': 92.4,
        'Invulnerability Time Period (Seconds)': 1,
    },
    {
        'Number of Boosts': 20,
        'Base Health': 500,
        'Speed of the Player (Number Frames to HalfScreen Distance)': 92,
        'Invulnerability Time Period (Seconds)': 1,
    },
    {
        'Number of Boosts': 21,
        'Base Health': 520,
        'Speed of the Player (Number Frames to HalfScreen Distance)': 91.6,
        'Invulnerability Time Period (Seconds)': 1,
    },
    {
        'Number of Boosts': 22,
        'Base Health': 540,
        'Speed of the Player (Number Frames to HalfScreen Distance)': 91.2,
        'Invulnerability Time Period (Seconds)': 1,
    },
    {
        'Number of Boosts': 23,
        'Base Health': 560,
        'Speed of the Player (Number Frames to HalfScreen Distance)': 90.8,
        'Invulnerability Time Period (Seconds)': 1,
    },
    {
        'Number of Boosts': 24,
        'Base Health': 580,
        'Speed of the Player (Number Frames to HalfScreen Distance)': 90.4,
        'Invulnerability Time Period (Seconds)': 1,
    },
    {
        'Number of Boosts': 25,
        'Base Health': 600,
        'Speed of the Player (Number Frames to HalfScreen Distance)': 90,
        'Invulnerability Time Period (Seconds)': 1,
    },
] as const;

export default PlayerStats;
